[project]
name = "wgprestserver"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
restserver = "wangp_server.server:main"
restworker = "wangp_server.worker:main_worker"
restmodels = "wangp_server.worker:main_models"
restdefaults = "wangp_server.worker:main_defaults"

